// Copyright 2022 VMware, Inc.
// SPDX-License-Identifier: MIT
pub mod affinity;
pub mod api_method;
pub mod api_resource;
pub mod common;
pub mod config_map;
pub mod container;
pub mod daemon_set;
pub mod dynamic;
pub mod label_selector;
pub mod marshal;
pub mod object_meta;
pub mod owner_reference;
pub mod persistent_volume_claim;
pub mod pod;
pub mod pod_template_spec;
pub mod prelude;
pub mod resource;
pub mod resource_requirements;
pub mod role;
pub mod role_binding;
pub mod secret;
pub mod service;
pub mod service_account;
pub mod stateful_set;
pub mod toleration;
pub mod volume;
