apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: simple
  name: simple
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: simple-controller
  namespace: simple
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: simple-controller
  name: simple-controller-role
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - serviceaccounts
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - update
      - watch
  - apiGroups:
      - anvil.dev
    resources:
      - simplecrs
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - anvil.dev
    resources:
      - simplecrs/finalizers
    verbs:
      - update
  - apiGroups:
      - anvil.dev
    resources:
      - simplecrs/status
    verbs:
      - get
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
    verbs:
      - create
      - get
      - list
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - create
      - get
      - list
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: simple-controller
  name: simple-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: simple-controller-role
subjects:
  - kind: ServiceAccount
    name: simple-controller
    namespace: simple
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-controller
  namespace: simple
  labels:
    app.kubernetes.io/name: simple-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: simple-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: simple-controller
    spec:
      containers:
        - image: ghcr.io/vmware-research/verifiable-controllers/simple-controller:latest
          name: controller
          command:
            - simple-controller
            - run
          resources:
            limits:
              cpu: 200m
              memory: 500Mi
            requests:
              cpu: 200m
              memory: 500Mi
      serviceAccountName: simple-controller
