apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: simplecrs.anvil.dev
spec:
  group: anvil.dev
  names:
    kind: SimpleCR
    plural: simplecrs
    shortNames:
    - cmg
    singular: simplecr
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              content:
                type: string
