apiVersion: apps/v1
kind: Deployment
metadata:
  name: vreplicaset-controller
  namespace: vreplicaset
  labels:
    app.kubernetes.io/name: vreplicaset-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: vreplicaset-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: vreplicaset-controller
    spec:
      containers:
        - image: local/vreplicaset-controller:v0.1.0
          imagePullPolicy: IfNotPresent
          name: controller
      serviceAccountName: vreplicaset-controller
