apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: vreplicaset
  name: vreplicaset
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vreplicaset-controller
  namespace: vreplicaset
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vreplicaset-controller
  name: vreplicaset-controller-role
rules:
  - apiGroups:
      - anvil.dev
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: vreplicaset-controller
  name: vreplicaset-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vreplicaset-controller-role
subjects:
  - kind: ServiceAccount
    name: vreplicaset-controller
    namespace: vreplicaset
