apiVersion: apps/v1
kind: Deployment
metadata:
  name: consumer-controller
  namespace: consumer
  labels:
    app.kubernetes.io/name: consumer-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: consumer-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: consumer-controller
    spec:
      containers:
        - image: ghcr.io/vmware-research/verifiable-controllers/consumer-controller:latest
          name: controller
      serviceAccountName: consumer-controller
