apiVersion: anvil.dev/v1
kind: VReplicaSet
metadata:
  name: negative-replicas-reject
spec:
  replicas: -1
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: container-negative-replicas-reject
          image: nginx:latest
          ports:
            - containerPort: 80
