apiVersion: anvil.dev/v1
kind: VStatefulSet
metadata:
  name: invalid-pvc-retention-policy-reject
spec:
  serviceName: "test-app"
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: container
          image: nginx:latest
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: "Keep" 
    whenScaled: "Delete"