apiVersion: anvil.dev/v1
kind: VStatefulSet
metadata:
  name: missing-volume-claim-spec-reject
spec:
  serviceName: "test-app"
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: container
          image: nginx:latest
  volumeClaimTemplates:
    - metadata:
        name: data