apiVersion: anvil.dev/v1
kind: VDeployment
metadata:
  name: negative-progressdeadline
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
        - name: container-test
          image: nginx:latest
  progressDeadlineSeconds: -60