apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: rabbitmq
  name: rabbitmq
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: rabbitmq-controller
  namespace: rabbitmq
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: rabbitmq-controller
  name: rabbitmq-controller-role
rules:
  - apiGroups:
      - anvil.dev
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - events
      - configmaps
      - secrets
      - serviceaccounts
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - daemonsets
      - replicasets
      - statefulsets
    verbs:
      - "*"
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - "*"
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - rolebindings
      - roles
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: rabbitmq-controller
  name: rabbitmq-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: rabbitmq-controller-role
subjects:
  - kind: ServiceAccount
    name: rabbitmq-controller
    namespace: rabbitmq
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-controller
  namespace: rabbitmq
  labels:
    app.kubernetes.io/name: rabbitmq-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: rabbitmq-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rabbitmq-controller
    spec:
      containers:
        - image: local/rabbitmq-controller:v0.1.0
          imagePullPolicy: IfNotPresent
          name: controller
          command:
            - rabbitmq-controller
            - run
      serviceAccountName: rabbitmq-controller
