apiVersion: anvil.dev/v1
kind: RabbitmqCluster
metadata:
  name: rabbitmq
  namespace: default
spec:
  replicas: 3
  image: rabbitmq:3.11.10-management
  rabbitmqConfig:
    additionalConfig: |
      log.console.level = debug
  persistence:
    storage: 10Gi
    storageClassName:
