apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-controller
  namespace: zookeeper
  labels:
    app.kubernetes.io/name: zookeeper-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zookeeper-controller
    spec:
      containers:
        - image: ghcr.io/vmware-research/verifiable-controllers/zookeeper-controller:latest
          name: controller
      serviceAccountName: zookeeper-controller
