apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-controller
  namespace: zookeeper
  labels:
    app.kubernetes.io/name: zookeeper-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: zookeeper-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: zookeeper-controller
    spec:
      containers:
        - image: local/zookeeper-controller:v0.1.0
          imagePullPolicy: IfNotPresent
          name: controller
          command: ["/usr/local/bin/controller"]
          args: ["crash"]
      serviceAccountName: zookeeper-controller
