apiVersion: apps/v1
kind: Deployment
metadata:
  name: producer-controller
  namespace: producer
  labels:
    app.kubernetes.io/name: producer-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: producer-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: producer-controller
    spec:
      containers:
        - image: local/producer-controller:v0.1.0
          imagePullPolicy: IfNotPresent
          name: controller
      serviceAccountName: producer-controller
