apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: producer
  name: producer
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: producer-controller
  namespace: producer
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: producer-controller
  name: producer-controller-role
rules:
  - apiGroups:
      - anvil.dev
    resources:
      - "*"
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/name: producer-controller
  name: producer-controller-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: producer-controller-role
subjects:
  - kind: ServiceAccount
    name: producer-controller
    namespace: producer
