apiVersion: apps/v1
kind: Deployment
metadata:
  name: v2-vdeployment-controller
  namespace: v2-vdeployment
  labels:
    app.kubernetes.io/name: v2-vdeployment-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: v2-vdeployment-controller
  template:
    metadata:
      labels:
        app.kubernetes.io/name: v2-vdeployment-controller
    spec:
      containers:
        - image: local/v2-vdeployment-controller:v0.1.0
          imagePullPolicy: IfNotPresent
          name: controller
      serviceAccountName: v2-vdeployment-controller
