apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: "2023-07-08T21:03:12Z"
  generation: 1
  labels:
    app: zk
  name: zk
  namespace: default
  ownerReferences:
    - apiVersion: anvil.dev/v1
      controller: true
      kind: ZookeeperCluster
      name: zk
      uid: 71c152e9-24dd-475e-8e69-a79048da8674
  resourceVersion: "1053"
  uid: 6fce7e9c-2bff-4fff-b042-a7fb0351a1a5
spec:
  podManagementPolicy: OrderedReady
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: zk
  serviceName: zk-headless
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Delete
  template:
    metadata:
      creationTimestamp: null
      generateName: zk
      labels:
        app: zk
        kind: ZookeeperMember
    spec:
      containers:
        - command:
            - /usr/local/bin/zookeeperStart.sh
          image: pravega/zookeeper:0.2.14
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - zookeeperLive.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          name: zookeeper
          ports:
            - containerPort: 2181
              name: client
              protocol: TCP
            - containerPort: 2888
              name: quorum
              protocol: TCP
            - containerPort: 3888
              name: leader-election
              protocol: TCP
            - containerPort: 7000
              name: metrics
              protocol: TCP
            - containerPort: 8080
              name: admin-server
              protocol: TCP
          readinessProbe:
            exec:
              command:
                - zookeeperReady.sh
            failureThreshold: 3
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 10
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /data
              name: data
            - mountPath: /conf
              name: conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: zk-configmap
          name: conf
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        creationTimestamp: null
        labels:
          app: zk
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
        volumeMode: Filesystem
      status:
        phase: Pending
status:
  availableReplicas: 4
  collisionCount: 0
  currentReplicas: 4
  currentRevision: zk-6c8485fb99
  observedGeneration: 1
  readyReplicas: 4
  replicas: 4
  updateRevision: zk-6c8485fb99
  updatedReplicas: 4
kubectl patch statefulset zk --type json -p='[{"op": "replace", "path": "/spec/persistentVolumeClaimRetentionPolicy/whenScaled", "value": "Delete"}]'
