apiVersion: v1
kind: Namespace
metadata:
  labels:
    app.kubernetes.io/name: fluent
  name: fluent
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: operator
    app.kubernetes.io/name: fluent-operator
  name: fluent-operator
  namespace: fluent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: fluent-operator
  name: fluent-operator
rules:
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - statefulsets
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
      - serviceaccounts
      - configmaps
      - services
      - namespaces
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - fluentbit.fluent.io
    resources:
      - collectors
      - fluentbits
      - clusterfluentbitconfigs
      - clusterfilters
      - clusterinputs
      - clusteroutputs
      - clusterparsers
      - fluentbitconfigs
      - filters
      - outputs
      - parsers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - fluentd.fluent.io
    resources:
      - fluentds
      - fluentds/status
      - clusterfluentdconfigs
      - clusterfluentdconfigs/status
      - fluentdconfigs
      - fluentdconfigs/status
      - clusterfilters
      - filters
      - clusteroutputs
      - outputs
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterrolebindings
    verbs:
      - create
      - list
      - get
      - watch
      - patch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - clusterroles
    verbs:
      - create
      - list
      - get
      - watch
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: fluent-operator
  name: fluent-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-operator
subjects:
  - kind: ServiceAccount
    name: fluent-operator
    namespace: fluent
