apiVersion: anvil.dev/v1
kind: VDeployment
metadata:
  name: unmatched-matchlabels-reject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-app
      env: dev
  template:
    metadata:
      labels:
        app: test-app
        env: prod
    spec:
      containers:
        - name: container-unmatched-matchlabels-reject
          image: nginx:latest
          ports:
            - containerPort: 80
