apiVersion: anvil.dev/v1
kind: RabbitmqCluster
metadata:
  name: test-cluster
  namespace: default
spec:
  image: rabbitmq:3.11.10-management
  persistence:
    storage: 10Gi
    storageClassName: null
  rabbitmqConfig:
    additionalConfig: 'log.console.level = debug'
  replicas: 3