#!/usr/bin/env bash

## Fetch, build, and wire up Verus for this repo.
##
## VERUS_DIR: existing checkout to build, or where to clone one. Default: <repo>/.verus

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
VERUS_DIR="${VERUS_DIR:-$PROJECT_DIR/.verus}"

if [ ! -d "$VERUS_DIR/.git" ]; then
    git clone --depth 1 --recurse-submodules --shallow-submodules \
        https://github.com/verus-lang/verus "$VERUS_DIR"
fi

cd "$VERUS_DIR/source"
rustc --version

[ -f z3 ] || ./tools/get-z3.sh
# shellcheck disable=SC1091
source ../tools/activate
env VERUS_Z3_PATH="$PWD/z3" vargo build --release

VERUS_BIN_DIR="$VERUS_DIR/source/target-verus/release"

CHANNEL="$(grep -m1 '^channel' "$VERUS_DIR/rust-toolchain.toml" | sed -E 's/channel *= *"([^"]+)"/\1/')"

# do not hand-edit; regenerate by re-running this script
{
    echo "# AUTO-GENERATED by tools/setup-verus.sh"
    echo "[toolchain]"
    echo "channel = \"$CHANNEL\""
} >"$PROJECT_DIR/rust-toolchain.toml"

echo "export PATH=\"$VERUS_BIN_DIR:\$PATH\""
