#[path = "external_shim_layer/mod.rs"]
pub mod external_shim_layer;
pub mod kubernetes_api_objects;
#[path = "kubernetes_cluster/mod.rs"]
pub mod kubernetes_cluster;
#[path = "reconciler/mod.rs"]
pub mod reconciler;
#[path = "shim_layer/mod.rs"]
pub mod shim_layer;
pub mod state_machine;
pub mod temporal_logic;
pub mod vstd_ext;
#[path = "controllers/vdeployment_controller/mod.rs"]
pub mod vdeployment_controller;
#[path = "controllers/vreplicaset_controller/mod.rs"]
pub mod vreplicaset_controller;
#[path = "controllers/vstatefulset_controller/mod.rs"]
pub mod vstatefulset_controller;
#[path = "controllers/composition/mod.rs"]
pub mod composition;

fn main() {}