name: Continuous integration
run-name: Continuous integration run by ${{ github.actor }}
on:
  # push:
  #   branches:
  #     - main
  #   paths-ignore:
  #     - "README.md"
  #     - ".gitignore"
  #     - "doc/**"
  pull_request:
  merge_group:
  workflow_dispatch:
env:
  verus_release: "https://github.com/verus-lang/verus/releases/download/release%2F0.2025.06.22.585827c/verus-0.2025.06.22.585827c-x86-linux.zip"
  kind_version: 0.23.0
  go_version: "^1.20"

jobs:
  vreplicaset-verification:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          . "~/.cargo/env" && rustup toolchain install
      - name: Download Verus
        run: |
          curl -L --output verus-x86-linux.zip ${{ env.verus_release }}
          unzip verus-x86-linux.zip && mv verus-x86-linux ../verus && export VERUS_DIR="../verus"
      - name: Verify vreplicaset controller
        run: ./build.sh vreplicaset_controller.rs --rlimit 50 --time
  vdeployment-verification:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          . "~/.cargo/env" && rustup toolchain install
      - name: Download Verus
        run: |
          curl -L --output verus-x86-linux.zip ${{ env.verus_release }}
          unzip verus-x86-linux.zip && mv verus-x86-linux ../verus && export VERUS_DIR="../verus"
      - name: Verify vdeployment controller
        run: ./build.sh vdeployment_controller.rs --rlimit 50 --time
  vstatefulset-verification:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          . "~/.cargo/env" && rustup toolchain install
      - name: Download Verus
        run: |
          curl -L --output verus-x86-linux.zip ${{ env.verus_release }}
          unzip verus-x86-linux.zip && mv verus-x86-linux ../verus && export VERUS_DIR="../verus"
      - name: Verify vstatefulset controller
        run: ./build.sh vstatefulset_controller.rs --rlimit 50 --time
  vreplicaset-admission-verification:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          . "~/.cargo/env" && rustup toolchain install
      - name: Download Verus
        run: |
          curl -L --output verus-x86-linux.zip ${{ env.verus_release }}
          unzip verus-x86-linux.zip && mv verus-x86-linux ../verus && export VERUS_DIR="../verus"
      - name: Verify vreplicaset admission controller
        run: ./build.sh vreplicaset_admission_controller.rs --rlimit 50 --time
  vstatefulset-admission-verification:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          . "~/.cargo/env" && rustup toolchain install
      - name: Download Verus
        run: |
          curl -L --output verus-x86-linux.zip ${{ env.verus_release }}
          unzip verus-x86-linux.zip && mv verus-x86-linux ../verus && export VERUS_DIR="../verus"
      - name: Verify vstatefulset admission controller
        run: ./build.sh vstatefulset_admission_controller.rs --rlimit 50 --time
  vdeployment-admission-verification:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          . "~/.cargo/env" && rustup toolchain install
      - name: Download Verus
        run: |
          curl -L --output verus-x86-linux.zip ${{ env.verus_release }}
          unzip verus-x86-linux.zip && mv verus-x86-linux ../verus && export VERUS_DIR="../verus"
      - name: Verify vdeployment admission controller
        run: ./build.sh vdeployment_admission_controller.rs --rlimit 50 --time
  framework-verification:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          . "~/.cargo/env" && rustup toolchain install
      - name: Download Verus
        run: |
          curl -L --output verus-x86-linux.zip ${{ env.verus_release }}
          unzip verus-x86-linux.zip && mv verus-x86-linux ../verus && export VERUS_DIR="../verus"
      - name: Verify conformance of the executable model
        run: ./build.sh anvil.rs --crate-type lib --rlimit 50 --
  vreplicaset-admission-e2e-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          . "~/.cargo/env" && rustup toolchain install
      - name: Download Verus
        run: |
          curl -L --output verus-x86-linux.zip ${{ env.verus_release }}
          unzip verus-x86-linux.zip && mv verus-x86-linux ../verus && export VERUS_DIR="../verus"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}
      - name: Install kind
        run: go install sigs.k8s.io/kind@v$kind_version
      - name: Deploy vreplicaset admission controller
        run: ./local-test.sh vreplicaset-admission --build
      - name: Run vreplicaset e2e tests for admission
        run: . "$HOME/.cargo/env" && cd e2e && cargo run -- vreplicaset-admission
  vstatefulset-admission-e2e-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          . "~/.cargo/env" && rustup toolchain install
      - name: Download Verus
        run: |
          curl -L --output verus-x86-linux.zip ${{ env.verus_release }}
          unzip verus-x86-linux.zip && mv verus-x86-linux ../verus && export VERUS_DIR="../verus"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}
      - name: Install kind
        run: go install sigs.k8s.io/kind@v$kind_version
      - name: Deploy vstatefulset admission controller
        run: ./local-test.sh vstatefulset-admission --build
      - name: Run vstatefulset e2e tests for admission
        run: . "$HOME/.cargo/env" && cd e2e && cargo run -- vstatefulset-admission
  vdeployment-admission-e2e-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          . "~/.cargo/env" && rustup toolchain install
      - name: Download Verus
        run: |
          curl -L --output verus-x86-linux.zip ${{ env.verus_release }}
          unzip verus-x86-linux.zip && mv verus-x86-linux ../verus && export VERUS_DIR="../verus"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}
      - name: Install kind
        run: go install sigs.k8s.io/kind@v$kind_version
      - name: Deploy vdeployment admission controller
        run: ./local-test.sh vdeployment-admission --build
      - name: Run vdeployment e2e tests for admission
        run: . "$HOME/.cargo/env" && cd e2e && cargo run -- vdeployment-admission
  vreplicaset-e2e-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          . "~/.cargo/env" && rustup toolchain install
      - name: Download Verus
        run: |
          curl -L --output verus-x86-linux.zip ${{ env.verus_release }}
          unzip verus-x86-linux.zip && mv verus-x86-linux ../verus && export VERUS_DIR="../verus"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.go_version }}
      - name: Install kind
        run: go install sigs.k8s.io/kind@v$kind_version
      - name: Deploy vreplicaset controller
        run: ./local-test.sh vreplicaset --build-remote
      - name: Run vreplicaset e2e tests
        run: . "$HOME/.cargo/env" && cd e2e && cargo run -- vreplicaset
  vdeployment-e2e-test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust Toolchain
        run: |
          curl --proto '=https' --tlsv1.2 --retry 10 --retry-connrefused -fsSL "https://sh.rustup.rs" | sh -s -- --default-toolchain none -y
          . "~/.cargo/env" && rustup toolchain install
      - name: Download Verus
        run: |
          curl -L --output verus-x86-linux.zip ${{ env.verus_release }}
          unzip verus-x86-linux.zip && mv verus-x86-linux ../verus && export VERUS_DIR="../verus"
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: "^1.20"
      - name: Install kind
        run: go install sigs.k8s.io/kind@v0.23.0
      - name: Deploy vdeployment controller
        run: ./local-test.sh vdeployment --build
      - name: Run vdeployment e2e tests
        run: . "$HOME/.cargo/env" && cd e2e && cargo run -- vdeployment