name: Delete package
on:
  workflow_dispatch:
    inputs:
      image:
        description: 'Name of the image to be deleted'
        required: true
        type: string
jobs:
  delete-package:
    runs-on: ubuntu-20.04
    permissions:
        packages: write
    steps:
      - name: Delete packages
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
            gh api --method DELETE -H "Accept: application/vnd.github+json" -H "X-GitHub-Api-Version: 2022-11-28" /orgs/vmware-research/packages/container/verifiable-controllers%2F${{ inputs.image }}
