name: Verus build
on:
  workflow_dispatch:
env:
  IMAGE_NAME: ${{ github.repository }}
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log into registry ghcr.io
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      - name: Build Verus image
        run: |
          cd docker/verus
          docker build -t ghcr.io/${{ env.IMAGE_NAME }}/verus:latest --build-arg VERUS_VER=3b6b805ac .
          docker tag ghcr.io/${{ env.IMAGE_NAME }}/verus:latest ghcr.io/${{ env.IMAGE_NAME }}/verus:3b6b805ac
      - name: Push Verus image
        run: |
          docker push ghcr.io/${{ env.IMAGE_NAME }}/verus:latest
          docker push ghcr.io/${{ env.IMAGE_NAME }}/verus:3b6b805ac
